// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Portal.Domain.Enums;
using Portal.Infrastructure.Persistence;

#nullable disable

namespace Portal.Infrastructure.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20260805165305_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_inmueble", new[] { "borrador", "publicado", "pausado", "archivado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_lead", new[] { "nuevo", "contactado", "descartado", "cerrado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_operacion", new[] { "disponible", "reservado", "cerrado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "politica_mascotas", new[] { "permitidas", "no_permitidas", "con_restricciones" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "rol_usuario", new[] { "admin", "asesor" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_operacion", new[] { "venta", "arriendo" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_ubicacion", new[] { "zona", "localidad", "upz", "barrio" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portal.Domain.Entities.Caracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<bool>("Filtrable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("filtrable");

                    b.Property<string>("Icono")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("icono");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoValor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("booleano")
                        .HasColumnName("tipo_valor");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId", "Nombre")
                        .IsUnique();

                    b.ToTable("caracteristicas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Filtrable = true,
                            Icono = "kitchen",
                            Nombre = "Cocina integral",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 1,
                            Filtrable = true,
                            Icono = "water-heater",
                            Nombre = "Calentador",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 1,
                            Filtrable = false,
                            Icono = "closet",
                            Nombre = "Closets",
                            TipoValor = "numero"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 1,
                            Filtrable = true,
                            Icono = "balcony",
                            Nombre = "Balcón",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 1,
                            Filtrable = true,
                            Icono = "terrace",
                            Nombre = "Terraza",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 1,
                            Filtrable = false,
                            Icono = "study",
                            Nombre = "Estudio",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 1,
                            Filtrable = false,
                            Icono = "storage",
                            Nombre = "Depósito",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 1,
                            Filtrable = false,
                            Icono = "fireplace",
                            Nombre = "Chimenea",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaId = 2,
                            Filtrable = true,
                            Icono = "elevator",
                            Nombre = "Ascensor",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaId = 2,
                            Filtrable = true,
                            Icono = "pool",
                            Nombre = "Piscina",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CategoriaId = 2,
                            Filtrable = true,
                            Icono = "gym",
                            Nombre = "Gimnasio",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CategoriaId = 2,
                            Filtrable = false,
                            Icono = "community-room",
                            Nombre = "Salón comunal",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            CategoriaId = 2,
                            Filtrable = false,
                            Icono = "playground",
                            Nombre = "Parque infantil",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            CategoriaId = 2,
                            Filtrable = false,
                            Icono = "bbq",
                            Nombre = "Zona BBQ",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            CategoriaId = 2,
                            Filtrable = false,
                            Icono = "court",
                            Nombre = "Cancha múltiple",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            CategoriaId = 3,
                            Filtrable = true,
                            Icono = "wifi",
                            Nombre = "Internet incluido",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            CategoriaId = 3,
                            Filtrable = true,
                            Icono = "gas",
                            Nombre = "Gas natural",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            CategoriaId = 3,
                            Filtrable = false,
                            Icono = "ac",
                            Nombre = "Aire acondicionado",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            CategoriaId = 4,
                            Filtrable = true,
                            Icono = "security",
                            Nombre = "Vigilancia 24h",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            CategoriaId = 4,
                            Filtrable = true,
                            Icono = "doorman",
                            Nombre = "Portería",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            CategoriaId = 4,
                            Filtrable = false,
                            Icono = "cctv",
                            Nombre = "CCTV",
                            TipoValor = "booleano"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            CategoriaId = 4,
                            Filtrable = false,
                            Icono = "alarm",
                            Nombre = "Alarma",
                            TipoValor = "booleano"
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.CategoriaCaracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<short>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("categorias_caracteristica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Interior",
                            Orden = (short)1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Zonas comunes",
                            Orden = (short)2
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Servicios",
                            Orden = (short)3
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Seguridad",
                            Orden = (short)4
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.Imagen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EsPortada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_portada");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("formato");

                    b.Property<long>("InmuebleId")
                        .HasColumnType("bigint")
                        .HasColumnName("inmueble_id");

                    b.Property<short>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("orden");

                    b.Property<int?>("PesoBytes")
                        .HasColumnType("integer")
                        .HasColumnName("peso_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("TextoAlt")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("texto_alt");

                    b.Property<string>("UrlCdn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_cdn");

                    b.Property<string>("UrlThumbnail")
                        .HasColumnType("text")
                        .HasColumnName("url_thumbnail");

                    b.HasKey("Id");

                    b.HasIndex("InmuebleId")
                        .IsUnique()
                        .HasDatabaseName("idx_una_portada")
                        .HasFilter("es_portada = TRUE");

                    b.HasIndex("InmuebleId", "Orden")
                        .HasDatabaseName("idx_imagenes_inmueble");

                    b.ToTable("imagenes", (string)null);
                });

            modelBuilder.Entity("Portal.Domain.Entities.Inmueble", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Amoblado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("no")
                        .HasColumnName("amoblado");

                    b.Property<string>("Antiguedad")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("antiguedad");

                    b.Property<decimal?>("AreaConstruidaM2")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("area_construida_m2");

                    b.Property<decimal?>("AreaPrivadaM2")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("area_privada_m2");

                    b.Property<long?>("AsesorId")
                        .HasColumnType("bigint")
                        .HasColumnName("asesor_id");

                    b.Property<short>("Banos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("banos");

                    b.Property<NpgsqlTsVector>("BusquedaTsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("busqueda_tsv")
                        .HasComputedColumnSql("setweight(to_tsvector('spanish', coalesce(titulo, '')), 'A') || setweight(to_tsvector('spanish', coalesce(codigo_referencia, '')), 'A') || setweight(to_tsvector('spanish', coalesce(descripcion, '')), 'B')", true);

                    b.Property<string>("CodigoReferencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_referencia");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CreadoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Destacado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("destacado");

                    b.Property<string>("DireccionExacta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion_exacta");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<EstadoInmueble>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_inmueble")
                        .HasDefaultValue(EstadoInmueble.Borrador)
                        .HasColumnName("estado");

                    b.Property<short?>("Estrato")
                        .HasColumnType("smallint")
                        .HasColumnName("estrato");

                    b.Property<short>("Habitaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("habitaciones");

                    b.Property<decimal>("LatitudAproximada")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitud_aproximada");

                    b.Property<decimal?>("LatitudExacta")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitud_exacta");

                    b.Property<decimal>("LongitudAproximada")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitud_aproximada");

                    b.Property<decimal?>("LongitudExacta")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitud_exacta");

                    b.Property<string>("MatriculaInmobiliaria")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("matricula_inmobiliaria");

                    b.Property<string>("MetaDescripcion")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("meta_descripcion");

                    b.Property<string>("MetaTitulo")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("meta_titulo");

                    b.Property<string>("Orientacion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("orientacion");

                    b.Property<short>("Parqueaderos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("parqueaderos");

                    b.Property<short?>("Piso")
                        .HasColumnType("smallint")
                        .HasColumnName("piso");

                    b.Property<short?>("PisosEdificio")
                        .HasColumnType("smallint")
                        .HasColumnName("pisos_edificio");

                    b.Property<PoliticaMascotas>("PoliticaMascotas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("politica_mascotas")
                        .HasDefaultValue(PoliticaMascotas.NoPermitidas)
                        .HasColumnName("politica_mascotas");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.Property<int>("TipoInmuebleId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_inmueble_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("titulo");

                    b.Property<long>("UbicacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("Id");

                    b.HasIndex("AsesorId");

                    b.HasIndex("BusquedaTsv")
                        .HasDatabaseName("idx_inmuebles_tsv");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BusquedaTsv"), "gin");

                    b.HasIndex("CodigoReferencia")
                        .IsUnique();

                    b.HasIndex("CreadoPor");

                    b.HasIndex("Destacado")
                        .HasDatabaseName("idx_inmuebles_destacado")
                        .HasFilter("estado = 'publicado'");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TipoInmuebleId");

                    b.HasIndex("UbicacionId");

                    b.HasIndex("LatitudAproximada", "LongitudAproximada")
                        .HasDatabaseName("idx_inmuebles_geo");

                    b.HasIndex("Estado", "TipoInmuebleId", "UbicacionId", "Estrato")
                        .HasDatabaseName("idx_inmuebles_filtros")
                        .HasFilter("eliminado_en IS NULL");

                    b.ToTable("inmuebles", null, t =>
                        {
                            t.HasCheckConstraint("ck_inmuebles_estrato", "estrato BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.InmuebleCaracteristica", b =>
                {
                    b.Property<long>("InmuebleId")
                        .HasColumnType("bigint")
                        .HasColumnName("inmueble_id");

                    b.Property<int>("CaracteristicaId")
                        .HasColumnType("integer")
                        .HasColumnName("caracteristica_id");

                    b.Property<string>("Valor")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("valor");

                    b.HasKey("InmuebleId", "CaracteristicaId");

                    b.HasIndex("CaracteristicaId")
                        .HasDatabaseName("idx_inm_caract_caract");

                    b.ToTable("inmueble_caracteristicas", (string)null);
                });

            modelBuilder.Entity("Portal.Domain.Entities.InmuebleHistorial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("campo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("InmuebleId")
                        .HasColumnType("bigint")
                        .HasColumnName("inmueble_id");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id");

                    b.HasIndex("InmuebleId")
                        .HasDatabaseName("idx_inmueble_historial_inmueble");

                    b.HasIndex("UsuarioId");

                    b.ToTable("inmueble_historial", (string)null);
                });

            modelBuilder.Entity("Portal.Domain.Entities.InmuebleOperacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<bool>("AdminIncluida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("admin_incluida");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("CuotaAdministracion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cuota_administracion");

                    b.Property<EstadoOperacion>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_operacion")
                        .HasDefaultValue(EstadoOperacion.Disponible)
                        .HasColumnName("estado");

                    b.Property<long>("InmuebleId")
                        .HasColumnType("bigint")
                        .HasColumnName("inmueble_id");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("precio");

                    b.Property<TipoOperacion>("TipoOperacion")
                        .HasColumnType("tipo_operacion")
                        .HasColumnName("tipo_operacion");

                    b.HasKey("Id");

                    b.HasIndex("InmuebleId", "TipoOperacion")
                        .IsUnique();

                    b.HasIndex("TipoOperacion", "Precio", "Estado")
                        .HasDatabaseName("idx_operaciones_filtro")
                        .HasFilter("activo = TRUE");

                    b.ToTable("inmueble_operaciones", (string)null);
                });

            modelBuilder.Entity("Portal.Domain.Entities.Lead", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AceptoTratamientoDatos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("acepto_tratamiento_datos");

                    b.Property<long?>("AsignadoA")
                        .HasColumnType("bigint")
                        .HasColumnName("asignado_a");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<EstadoLead>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_lead")
                        .HasDefaultValue(EstadoLead.Nuevo)
                        .HasColumnName("estado");

                    b.Property<long?>("InmuebleId")
                        .HasColumnType("bigint")
                        .HasColumnName("inmueble_id");

                    b.Property<IPAddress>("IpOrigen")
                        .HasColumnType("inet")
                        .HasColumnName("ip_origen");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("origen");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("utm_campaign");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("utm_source");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoA");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_leads_estado");

                    b.HasIndex("InmuebleId")
                        .HasDatabaseName("idx_leads_inmueble");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("Portal.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_en");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_prt_usuario");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Portal.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acceso total al sistema",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gestión de propiedades y leads asignados",
                            Name = "Asesor"
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.TipoInmueble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.Property<short>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("orden");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tipos_inmueble", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Apartamento",
                            Orden = (short)1,
                            Slug = "apartamento"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Casa",
                            Orden = (short)2,
                            Slug = "casa"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Apartaestudio",
                            Orden = (short)3,
                            Slug = "apartaestudio"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Local",
                            Orden = (short)4,
                            Slug = "local"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Oficina",
                            Orden = (short)5,
                            Slug = "oficina"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Bodega",
                            Orden = (short)6,
                            Slug = "bodega"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Lote",
                            Orden = (short)7,
                            Slug = "lote"
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<long?>("PadreId")
                        .HasColumnType("bigint")
                        .HasColumnName("padre_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<TipoUbicacion>("Tipo")
                        .HasColumnType("tipo_ubicacion")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PadreId")
                        .HasDatabaseName("idx_ubicaciones_padre");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("idx_ubicaciones_tipo");

                    b.HasIndex("Tipo", "Slug", "PadreId")
                        .IsUnique();

                    b.ToTable("ubicaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Norte",
                            Slug = "norte",
                            Tipo = TipoUbicacion.Zona
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Noroccidente",
                            Slug = "noroccidente",
                            Tipo = TipoUbicacion.Zona
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Occidente",
                            Slug = "occidente",
                            Tipo = TipoUbicacion.Zona
                        },
                        new
                        {
                            Id = 4L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Centro",
                            Slug = "centro",
                            Tipo = TipoUbicacion.Zona
                        },
                        new
                        {
                            Id = 5L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Sur",
                            Slug = "sur",
                            Tipo = TipoUbicacion.Zona
                        },
                        new
                        {
                            Id = 6L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Suroccidente",
                            Slug = "suroccidente",
                            Tipo = TipoUbicacion.Zona
                        },
                        new
                        {
                            Id = 7L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Usaquén",
                            PadreId = 1L,
                            Slug = "usaquen",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 8L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Chapinero",
                            PadreId = 1L,
                            Slug = "chapinero",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 9L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Suba",
                            PadreId = 2L,
                            Slug = "suba",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 10L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Engativá",
                            PadreId = 2L,
                            Slug = "engativa",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 11L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Barrios Unidos",
                            PadreId = 2L,
                            Slug = "barrios-unidos",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 12L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Fontibón",
                            PadreId = 3L,
                            Slug = "fontibon",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 13L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Teusaquillo",
                            PadreId = 4L,
                            Slug = "teusaquillo",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 14L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Santa Fe",
                            PadreId = 4L,
                            Slug = "santa-fe",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 15L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "La Candelaria",
                            PadreId = 4L,
                            Slug = "la-candelaria",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 16L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Los Mártires",
                            PadreId = 4L,
                            Slug = "los-martires",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 17L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Puente Aranda",
                            PadreId = 6L,
                            Slug = "puente-aranda",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 18L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Kennedy",
                            PadreId = 6L,
                            Slug = "kennedy",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 19L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Bosa",
                            PadreId = 6L,
                            Slug = "bosa",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 20L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Antonio Nariño",
                            PadreId = 5L,
                            Slug = "antonio-narino",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 21L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Rafael Uribe Uribe",
                            PadreId = 5L,
                            Slug = "rafael-uribe-uribe",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 22L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Tunjuelito",
                            PadreId = 5L,
                            Slug = "tunjuelito",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 23L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "San Cristóbal",
                            PadreId = 5L,
                            Slug = "san-cristobal",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 24L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Usme",
                            PadreId = 5L,
                            Slug = "usme",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 25L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ciudad Bolívar",
                            PadreId = 5L,
                            Slug = "ciudad-bolivar",
                            Tipo = TipoUbicacion.Localidad
                        },
                        new
                        {
                            Id = 26L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Santa Bárbara",
                            PadreId = 7L,
                            Slug = "santa-barbara",
                            Tipo = TipoUbicacion.Upz
                        },
                        new
                        {
                            Id = 27L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Country Club",
                            PadreId = 7L,
                            Slug = "country-club",
                            Tipo = TipoUbicacion.Upz
                        },
                        new
                        {
                            Id = 28L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Chicó Lago",
                            PadreId = 8L,
                            Slug = "chico-lago",
                            Tipo = TipoUbicacion.Upz
                        },
                        new
                        {
                            Id = 29L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Chapinero Norte",
                            PadreId = 8L,
                            Slug = "chapinero-norte",
                            Tipo = TipoUbicacion.Upz
                        },
                        new
                        {
                            Id = 30L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Niza",
                            PadreId = 9L,
                            Slug = "niza",
                            Tipo = TipoUbicacion.Upz
                        },
                        new
                        {
                            Id = 31L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "El Prado",
                            PadreId = 9L,
                            Slug = "el-prado",
                            Tipo = TipoUbicacion.Upz
                        },
                        new
                        {
                            Id = 32L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Castilla",
                            PadreId = 18L,
                            Slug = "castilla",
                            Tipo = TipoUbicacion.Upz
                        },
                        new
                        {
                            Id = 33L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Santa Bárbara Occidental",
                            PadreId = 26L,
                            Slug = "santa-barbara-occidental",
                            Tipo = TipoUbicacion.Barrio
                        },
                        new
                        {
                            Id = 34L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Molinos Norte",
                            PadreId = 26L,
                            Slug = "molinos-norte",
                            Tipo = TipoUbicacion.Barrio
                        },
                        new
                        {
                            Id = 35L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Chicó Norte",
                            PadreId = 28L,
                            Slug = "chico-norte",
                            Tipo = TipoUbicacion.Barrio
                        },
                        new
                        {
                            Id = 36L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "El Retiro",
                            PadreId = 28L,
                            Slug = "el-retiro",
                            Tipo = TipoUbicacion.Barrio
                        },
                        new
                        {
                            Id = 37L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Quinta Camacho",
                            PadreId = 29L,
                            Slug = "quinta-camacho",
                            Tipo = TipoUbicacion.Barrio
                        },
                        new
                        {
                            Id = 38L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Niza Sur",
                            PadreId = 30L,
                            Slug = "niza-sur",
                            Tipo = TipoUbicacion.Barrio
                        },
                        new
                        {
                            Id = 39L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Colina Campestre",
                            PadreId = 30L,
                            Slug = "colina-campestre",
                            Tipo = TipoUbicacion.Barrio
                        },
                        new
                        {
                            Id = 40L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Prado Veraniego",
                            PadreId = 31L,
                            Slug = "prado-veraniego",
                            Tipo = TipoUbicacion.Barrio
                        },
                        new
                        {
                            Id = 41L,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Castilla Central",
                            PadreId = 32L,
                            Slug = "castilla-central",
                            Tipo = TipoUbicacion.Barrio
                        });
                });

            modelBuilder.Entity("Portal.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("RefreshTokenExpira")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expira");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.Property<RolUsuario>("Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("rol_usuario")
                        .HasDefaultValue(RolUsuario.Asesor)
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Rol")
                        .HasDatabaseName("idx_usuarios_rol")
                        .HasFilter("activo = TRUE");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Portal.Domain.Entities.Caracteristica", b =>
                {
                    b.HasOne("Portal.Domain.Entities.CategoriaCaracteristica", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Portal.Domain.Entities.Imagen", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Inmueble", null)
                        .WithMany()
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portal.Domain.Entities.Inmueble", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AsesorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Portal.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Portal.Domain.Entities.TipoInmueble", null)
                        .WithMany()
                        .HasForeignKey("TipoInmuebleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Portal.Domain.Entities.Ubicacion", null)
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Portal.Domain.Entities.InmuebleCaracteristica", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Caracteristica", null)
                        .WithMany()
                        .HasForeignKey("CaracteristicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Portal.Domain.Entities.Inmueble", null)
                        .WithMany()
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portal.Domain.Entities.InmuebleHistorial", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Inmueble", null)
                        .WithMany()
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Portal.Domain.Entities.InmuebleOperacion", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Inmueble", null)
                        .WithMany()
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portal.Domain.Entities.Lead", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AsignadoA")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Portal.Domain.Entities.Inmueble", null)
                        .WithMany()
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Portal.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portal.Domain.Entities.Ubicacion", b =>
                {
                    b.HasOne("Portal.Domain.Entities.Ubicacion", null)
                        .WithMany()
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
